import { aboutUs } from "../components/about-us.js";
import { blog } from "../components/blog.js";
import { clientLogos } from "../components/client-logos.js";
import { contactUs } from "../components/contact-us.js";
import { faq } from "../components/faq.js";
import { footer } from "../components/footer.js";
import { header } from "../components/header.js";
import { hero } from "../components/hero.js";
import { howItWorks } from "../components/how-it-works.js";
import { ourTeam } from "../components/our-team.js";
import { portfolioGalleryMultiSelect } from "../components/portfolio-gallery-multi.js";
import { portfolioGallery } from "../components/portfolio-gallery.js";
import { pricingPlan } from "../components/pricing-plan.js";
import { services } from "../components/services.js";
import { subscribe } from "../components/subscribe.js";
import { testimonials } from "../components/testimonials.js";

header();
hero();
aboutUs();
services();
portfolioGalleryMultiSelect();
portfolioGallery();
howItWorks();
testimonials();
ourTeam();
faq();
contactUs();
pricingPlan();
clientLogos();
blog();
subscribe();
footer();